/*
 * Main2.java
 *
 * Created on __DATE__, __TIME__
 */

package com.stone;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author  __USER__
 */
public class Main2 extends javax.swing.JFrame {

	private boolean buttonEable = true;
	
	/** Creates new form Main */
	public Main2() {
		initComponents();
		setTitle("删除文件");

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jTextField1 = new javax.swing.JTextField();
		jTextField1.setEnabled(false);
		jTextField2 = new javax.swing.JTextField();
		jTextField2.setEnabled(true);
		jTextField2.setText("在此处输入same频道名");
		
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(3);
		
		jTextField2.addMouseListener(new MouseListener() {
			
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			public void mouseClicked(MouseEvent e) {
				jTextField2.setText("");
			}
		});
		jButton1.addMouseListener(new MouseListener(){
			/**
			 * 点击事件
			 */
			public void mouseClicked(MouseEvent arg0) {
				if(buttonEable){
					// TODO Auto-generated method stub
					JFileChooser jfc = new JFileChooser();
					jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
					jfc.setDialogTitle("选择文件夹.");
				    if(jfc.showOpenDialog(Main2.this)==JFileChooser.APPROVE_OPTION ){
				    	//解释下这里,弹出个对话框,可以选择要上传的文件,如果选择了,就把选择的文件的绝对路径打印出来,有了绝对路径,通过JTextField的settext就能设置进去了,那个我没写
				    	System.out.println(jfc.getSelectedFile().getAbsolutePath());
				    	jTextField1.setText(jfc.getSelectedFile().getAbsolutePath());
				    }
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
			
		});
		
		
		jButton2.addMouseListener(new MouseListener(){
			/**
			 * 点击事件
			 */
			public void mouseClicked(MouseEvent arg0) {
				
				if(!buttonEable){
					return;
				}
				
				// TODO Auto-generated method stub
				final String filepath = jTextField1.getText().toString();
				if(filepath==null ||"".equals(filepath)){
					JOptionPane.showMessageDialog(null, "请选择文件");
					return;
				}
				
				final File file = new File(filepath);
				if(!file.isDirectory()){
					JOptionPane.showMessageDialog(null, "请选择文件夹");
					return;
				}
				
				String channelName = jTextField2.getText().toString().trim();
				if(channelName==null || "".equals(channelName)){
					JOptionPane.showMessageDialog(null, "请输入想要抓取的same频道名");
					return;
				}
				
				//启动线程
				Runnable t = new Runnable(){
					public void run() {
						jButton2.setEnabled(false);
						jButton1.setEnabled(false);
						jTextField2.setEditable(false);
						buttonEable = false;
						jTextArea1.setText("");
						jTextArea1.append("开始下载图片.\r\n");
						
//						ArrayList<File> allFiles = new ArrayList<File>();
//						each(allFiles,file.listFiles());
						try {
							SameImplBean.spiderSame(jTextField2.getText().toString(), null, filepath,jTextArea1);
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
						
						jTextArea1.append("结束执行.\r\n");
						
						jButton2.setEnabled(true);
						jButton1.setEnabled(true);
						jTextField2.setEditable(true);
						buttonEable = true;
					}
				};
				new Thread(t).start();
			}

			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
			
		});
		

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setText("选择文件夹");

		jButton2.setText("\u5f00\u59cb");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				395,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(
																				jButton1)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				30,
																				Short.MAX_VALUE)
																		.add(
																				jButton2))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jTextField2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				395,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		)

														.add(
																jScrollPane1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																573,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jButton1)
														.add(jButton2)
														.add(
																jTextField1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																30,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(18, 18, 18)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																jTextField2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																30,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																.add(18, 18, 18)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												232,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(19, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main2().setVisible(true);
			}
		});
	}
	

	public  void each(ArrayList<File> allFiles,File[] every) {
		for (File i : every) {
			
			if(i.isDirectory()){
				if (i.getName().equals(".svn")) {
					System.out.println();
//					allFiles.add(i);
					jTextArea1.append(i.getAbsolutePath()+"--"+delAllFile(i.getAbsolutePath())+"\r\n");
					jTextArea1.setCaretPosition(jTextArea1.getText().length());//滾動到底端 
				}else{
					each(allFiles, i.listFiles());
				}
			}
			
		}
	}
	

	public  boolean delAllFile(String path) {
		boolean flag = false;
		File file = new File(path);
		if (!file.exists()) {
			return flag;
		}
		if (!file.isDirectory()) {
			return flag;
		}
		String[] tempList = file.list();
		File temp = null;
		if(tempList.length==0){
			new File(path).delete();
			return true;
		}
		for (int i = 0; i < tempList.length; i++) {
			if (path.endsWith(File.separator)) {
				temp = new File(path + tempList[i]);
			} else {
				temp = new File(path + File.separator + tempList[i]);
			}
			if (temp.isFile()) {
				temp.delete();
			}
			if (temp.isDirectory()) {
				delAllFile(path + "/" + tempList[i]);// 先删除文件夹里面的文件
				delFolder(path + "/" + tempList[i]);// 再删除空文件夹
				flag = true;
			}
		}
		return flag;
	}
	

	public void delFolder(String folderPath) {
		try {
			delAllFile(folderPath); // 删除完里面所有内容
			String filePath = folderPath;
			filePath = filePath.toString();
			java.io.File myFilePath = new java.io.File(filePath);
			myFilePath.delete(); // 删除空文件夹
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public int totalCount(File f){
		
		String charset = new FileEncodeReferee(f).getCharset();
//		jTextArea1.append("编码格式."+charset+"\r\n");
		int count = 0;
		try {
			InputStream input = new FileInputStream(f);
			// ②
			InputStreamReader read = new InputStreamReader(input,charset);
			// ③
			BufferedReader r = new BufferedReader(read);
			// 读取下一行  如果读取的下一行为null  则内容结束
			while (true) {
				String t = r.readLine();
				if (t == null) {
					break;
				} else {
					count++;
//					jTextArea1.append(count+"."+t+"\r\n");
				}
			}
			r.close();
			read.close();
			input.close();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return count;
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}